### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by EricE** [fuzzysteve/CREST-Market-Downloader#1]
Hi,
This line:
inifile=os.path.dirname(**file**)+"downloader.ini"

Should be:
inifile=os.path.dirname(**file**)+os.sep+"downloader.ini"

Thanks for this!  Haven't actually run it yet, will do so tonight.

**Comment by fuzzysteve** [comment]
Ahhh.

I was thinking 'how can that be, it works fine for me'. But that's because I was always running it from inside the same directory. so it would. Thanks :) Fixed, and shuffled the lines around a bit, so all the imports are together at the top, rather than the inifile definition part way through.

I have a more comprehensive rewrite coming, which may improve performance. But we'll see.
